<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.5/dist/sweetalert2.all.min.js"></script>
<script>
  var klik = 0;
  var klikdeleted = 0;
    $(document).ready(function() {
        $("#loading").hide();
        $("#disablingDiv").hide();

      $("#divBlacklist").hide();
      $("#divDeleted").hide();
      $("#tabGenerate").addClass("selected-tab");

      // $('#TblBL').DataTable({
      //  "pageLength": 10,
      //  "order": [[ 1, 'desc' ]]
      // });
      // var t2 =  $('#TblBL').DataTable({
      //  "pageLength": 10,
      //  "order": [[ 1, 'desc' ]]
      // });
      
      // t2.on( 'order.dt search.dt', function () {
      //  t2.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
      //    cell.innerHTML = ''+(i+1)+'.';
      //  } );
      // } ).draw();    

      $("#tabBlacklist").click(function(){
        $("#tabGenerate").removeClass("selected-tab");
        $("#divGenerate").hide();
        $("#tabBlacklist").addClass("selected-tab");
        $("#divBlacklist").show();
        $("#tabDeletelist").removeClass("selected-tab");
        $("#divDeleted").hide();
        if(klik==0){
          blacklist();
        }
      });
      $("#tabGenerate").click(function(){
        $("#tabBlacklist").removeClass("selected-tab");
        $("#divBlacklist").hide();
        $("#tabGenerate").addClass("selected-tab");
        $("#divGenerate").show();
        $("#tabDeletelist").removeClass("selected-tab");
        $("#divDeleted").hide();
      }); 
      $("#tabDeletelist").click(function(){
        $("#tabBlacklist").removeClass("selected-tab");
        $("#divBlacklist").hide();
        $("#tabGenerate").removeClass("selected-tab");
        $("#divGenerate").hide();
        $("#tabDeletelist").addClass("selected-tab");
        $("#divDeleted").show();
        if(klikdeleted==0){
          deletedlist();
          klikdeleted++;
        }
      }); 
    });
</script>  

<style>
  .glyphicon { font-size:20px;margin-left:5px;margin-right:5px; }
  .merah { color:#c91006; }
  .hijau { color:#0ead05;}
  .generate-button {
    margin-left: 0px;
    margin-bottom:30px;
  }
  input { color:#000!important;}
  button { font-size: 14px; }
  .hd-tab { 
    float:left;width:200px;
    padding:10px;
    font-size:12px; 
    border-left:1px solid #ccc;border-top:1px solid #ccc;border-right:1px solid #ccc; 
    border-radius:10px 10px 0 0;
    cursor: pointer;
  }
  #divGenerate, #divBlacklist,#divDeleted {
    border:1px solid #ccc;
    padding:10px;
  }
  .selected-tab {
    background-color: #000;
    color: yellow;
  }
  .disablingDiv{
    z-index:1;
    
    /* make it cover the whole screen */
    position: fixed; 
    top: 0%; 
    left: 0%; 
    width: 100%; 
    height: 100%; 
    overflow: hidden;
    margin:0;
    /* make it white but fully transparent */
    background-color: white; 
    opacity:0.5;  
  }
  .loader {
    position: absolute;
    left: 50%;
    top: 50%;
    z-index: 1;
    margin: -75px 0 0 -75px;
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    width: 120px;
    height: 120px;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
  }

      @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
      }
</style>
<div id="disablingDiv" class="disablingDiv"></div>
<div id="loading" class="loader"></div>
<div class="container">
  <div>
    <div id="tabGenerate" class="hd-tab"><center>GENERATE UNIQUE CODE</center></div>
    <div id="tabBlacklist" class="hd-tab"><center>BLACKLIST NO SERI</center></div>
    <div id="tabDeletelist" class="hd-tab"><center>UNIQUE CODE DELETED</center></div>
  </div>
  <div style="clear:both;"></div>
  <div id="divGenerate">
    <div class="row generate-button" align="right" style="padding-right:50px;">
      <a href="<?=$controller?>/GenerateForm" target="_blank"><button>Generate Unique Code</button></a>
    </div>
    <div>
      <!-- <table id="TblSN" class="table table-striped table-bordered" cellspacing="0" width="100%"> -->
      <table id="TblSNList" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <caption>Generate Unique Code</caption>
<!--        <thead>
          <tr>
            <th width="5%"  class="hideOnMobile">ID</th>
            <th width="20%"  class="hideOnMobile">DATE</th>
            <th width="10%" class="hideOnMobile">Generated By</th>
            <th width="10%" class="hideOnMobile">Serial No. Min</th>
            <th width="10%" class="hideOnMobile">Serial No. Max</th>
            <th width="30%" class="hideOnMobile">Product ID</th>
            <th width="15%" class="hideOnMobile">Result</th>
            <th width="20%" class="hideOnMobile">Action</th>
            <th width="100%" class="colMobile">History</th>
            <th width="5%">Delete</th>
            <th width="5%">Blacklist</th>
          </tr>
        </thead>
        <tbody id="TblSN"> -->
          <?php
            // foreach($SNList as $sn) {
            //  $UCID = $sn->LogId;
            //  $DATE = $sn->LogDate;
            //  $CBY = $sn->CreatedBy;
            //  $SNMIN = $sn->SerialNoMin;
            //  $SNMAX = $sn->SerialNoMax;
            //  $PRODUCT = $sn->ProductID;
            //  $RESULT = $sn->Description;
              
            //  $ACTION = "";
            //  // if($_SESSION["can_read"] == 1) {
            //  //   if ($u->AlternateID!=0) {
            //  //     $ACTION .= "<a href = 'UserControllers/View/".$u->AlternateID."'><i class='glyphicon glyphicon-search'></i></a>";
            //  //   } else {
            //  //     $ACTION .= "<a href = 'UserControllers/View2/".urlencode($u->UserEmail)."'><i class='glyphicon glyphicon-search'></i></a>";
            //  //   }
            //  // }
            //  // if($_SESSION["can_update"] == 1) {
            //  //   if ($u->AlternateID!=0) {
            //  //     $ACTION .= "<a href = 'UserControllers/View/".$u->AlternateID."/1/1'><i class='glyphicon glyphicon-edit hijau'></i></a>";
            //  //   } else {
            //  //     $ACTION .= "<a href = 'UserControllers/View2/".urlencode($u->UserEmail)."/1/1'><i class='glyphicon glyphicon-edit hijau'></i></a>";              
            //  //   }
            //  // }
            //  // if($_SESSION["can_delete"] == 1) {
            //  //   if ($u->AlternateID!=0) {
            //  //     $ACTION .= "<a href = 'UserControllers/Disable/".$u->AlternateID."' data-toggle='modal' data-target='#confirm-delete' data-record-title='".$u->UserName."'><i class='glyphicon glyphicon-trash merah'></i></a>";
            //  //   } else {
            //  //     $ACTION .= "<a href = 'UserControllers/Disable2/".urlencode($u->UserEmail)."' data-toggle='modal' data-target='#confirm-delete' data-record-title='".$u->UserName."'><i class='glyphicon glyphicon-trash merah'></i></a>";              
            //  //   }
            //  // }
            //  $MOBILE = "#".$UCID."<br>".$DATE."<br>".$CBY."<br>".$SNMIN."<br>".$SNMAX."<br>".$PRODUCT."<br>".$RESULT;
              
              // echo "<tr id='row_".$UCID."'>"; 
              // echo "<td class='hideOnMobile'>".$UCID."</td>";
              // echo "<td class='hideOnMobile'>".$DATE."</td>";
              // echo "<td class='hideOnMobile'>".$CBY."</td>"; 
              // echo "<td class='hideOnMobile'>".$SNMIN."</td>"; 
              // echo "<td class='hideOnMobile'>".$SNMAX."</td>";
              // echo "<td class='hideOnMobile'>".$PRODUCT."</td>";
              // echo "<td class='hideOnMobile'>".$RESULT."</td>";
              // echo "<td>";
              // // if($CBY==$_SESSION["logged_in"]["useremail"]){
              // echo "<a href='javascript:HideCode(".$UCID.")'><i class='glyphicon glyphicon-trash'></a>";
              // // } else echo "-";
              // echo "</td>";
              // echo "<td>";
              // echo " <a href='UniqueCodegenerator/BlacklistAdd/".$UCID."' target='_blank'><i class='glyphicon glyphicon-ban-circle'></a>";
              
              // echo "</td>";
              // echo "<td width='100%' class='colMobile'>".$MOBILE."</td>";
              // echo "</tr>";
              
            // }
          ?>
        <!-- </tbody> -->
      </table>
    </div>
  </div>

  <div id="divBlacklist">
    <div class="row generate-button" align="right" style="padding-right:50px;">
      <a href="<?=$controller?>/BlacklistAdd"><button>Tambah Blacklist</button></a>
    </div>
    <div>
      <table id="TblBL" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th width="5%"  class="hideOnMobile">NO</th>
            <th width="20%"  class="hideOnMobile">DATE</th>
            <th width="10%" class="hideOnMobile">Generated By</th>
            <th width="10%" class="hideOnMobile">Serial No. Min</th>
            <th width="10%" class="hideOnMobile">Serial No. Max</th>
            <th width="30%" class="hideOnMobile">Product ID</th>
            <th width="15%" class="hideOnMobile">Message</th>
            <th width="15%" class="hideOnMobile">Message Internal</th>
            <!-- <th width="20%" class="hideOnMobile">Action</th> -->
            <th width="100%" class="colMobile">History</th>
            <th width="5%">Delete</th>
          </tr>
        </thead>
        <tbody id="TblSN">
          <?php
          // pindah ke js
            // $NO = 0;
            // foreach($Blacklist as $bl) {
              
            //   $NO++;
            //   $BLACKLIST_ID = $bl->blacklist_id;
            //   $CREATED_BY = $bl->created_by;
            //   $DATE = date('Y-m-d H:i:s', $bl->created_date->_seconds);
            //   $RANGE_AWAL = $bl->range_awal;
            //   $RANGE_AKHIR = $bl->range_akhir;
            //   $KODE_BRG = $bl->kode_brg;
            //   $MESSAGE = "";
            //   $MESSAGE = $bl->message;
            //   $MESSAGE_INTERNAL = $bl->message_internal;
            //   $MOBILE = "#".$BLACKLIST_ID."<br>".$DATE."<br>".$CREATED_BY."<br>".$RANGE_AWAL."<br>".$RANGE_AKHIR."<br>".$KODE_BRG."<br>".$MESSAGE."<br>".$MESSAGE_INTERNAL;
              
            //   echo "<tr id='row_".$NO."'>"; 
            //   echo "<td class='hideOnMobile'>".$NO."</td>";
            //   echo "<td class='hideOnMobile'>".$DATE."</td>";
            //   echo "<td class='hideOnMobile'>".$CREATED_BY."</td>"; 
            //   echo "<td class='hideOnMobile'>".$RANGE_AWAL."</td>"; 
            //   echo "<td class='hideOnMobile'>".$RANGE_AKHIR."</td>";
            //   echo "<td class='hideOnMobile'>".$KODE_BRG."</td>";
            //   echo "<td class='hideOnMobile'>".$MESSAGE."</td>";
            //   echo "<td class='hideOnMobile'>".$MESSAGE_INTERNAL."</td>";
            //   echo "<td>";
            //   if(strtoupper($CREATED_BY) == strtoupper($_SESSION["logged_in"]["username"])){
            //     echo "<a href = '#' data-href='".site_url()."/UniqueCodeGenerator/BlacklistDelete/".$BLACKLIST_ID."' data-toggle='modal' data-target='#confirm-delete' data-record-title='".$KODE_BRG." (No. Seri ".$RANGE_AWAL." sd ".$RANGE_AKHIR.")'><i class='glyphicon glyphicon-trash'></a>"; 
            //   } else echo "-";
            //   echo "</td>";
            //   echo "<td width='100%' class='colMobile'>".$MOBILE."</td>";
            //   echo "</tr>"; 
            // }
          ?>
        </tbody>
      </table>  
    </div> 

  </div>  

  <div id="divDeleted">
    <div>
      <table id="TblBLDeleted" class="table table-striped table-bordered" cellspacing="0" width="100%">
      </table>  
    </div> 
  </div>
</div> <!-- /container -->

<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        Konfirmasi Hapus Data Blacklist
      </div>
      <div class="modal-body">
        <p>Data <b><i class="title"></i></b> akan dihapus, dan tidak bisa dikembalikan.</p>
        <p>Lanjutkan menghapus?</p>
        <!-- <p class="debug-url"></p> -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <a class="btn btn-danger btn-ok">Delete</a>
      </div>
    </div>
  </div>
</div>

<script>
	
var table_blacklist;
	
  function HideCode(LogID){
    // var c = confirm("Delete Code Ini??");
    // if (c == true) {
    //   $.ajax({
    //     url:'UniqueCodegenerator/Hide/'+LogID,
    //     type:'POST',
    //     success:function(msg){
    //       if(msg== true){
    //         $('#row_'+LogID).hide();
    //       }
          
    //     }
    //   });
    // }

    Swal.fire({
      text: 'Apakah anda yakin ingin menghapus code ini?',
      input: 'text',
      inputAttributes: {
        autocapitalize: 'off'
      },
      showCancelButton: true,
      confirmButtonText: 'Deleted',
      showLoaderOnConfirm: true,
      allowOutsideClick: () => !Swal.isLoading()
    }).then((result) => {
      if (result.isConfirmed) {
        $.ajax({
          url:'<?=$controller ?>/Hide/'+LogID+'/'+result.value,
          type:'POST',
          success:function(msg){
            if(msg == 1){
              var dataTable = $('#TblSNList').DataTable();
                dataTable.destroy();
                datatables();
            }
            
          }
        });
      }
    })
  }

  $('#confirm-delete').on('show.bs.modal', function(e) {
    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
    $('.debug-url').html('Delete URL: <strong>' + $(this).find('.btn-ok').attr('href') + '</strong>');
  });
  
  $('#confirm-delete').on('show.bs.modal', function(e) {
    var data = $(e.relatedTarget).data();
    $('.title', this).text(data.recordTitle);
  });

  datatables();
  // $(document).ready(function() {
  function datatables(){
      $('#TblSNList').dataTable( {
          "bProcessing": true,
          "bServerSide": true,
           "columnDefs": [
            {"title":"ID","targets": 0,"className":"hideOnMobile"},
            {"title":"DATE","targets": 1,"className":"hideOnMobile"},
            {"title":"Generated By","targets": 2,"className":"hideOnMobile"},
            {"title":"Serial No. Min","targets": 3,"className":"hideOnMobile"},
            {"title":"Serial No. Max","targets": 4,"className":"hideOnMobile"},
            {"title":"Product ID","targets": 5,"className":"hideOnMobile"},
            {"title":"Brand","targets": 6,"className":"hideOnMobile"},
            {"title":"Result","targets": 7,"className":"hideOnMobile"},
            {"title":"History","targets": 8,"className":"colMobile"},
            {"title":"Delete","targets": 9, "orderable": false},
            {"title":"Blacklist","targets": 10, "orderable": false}
            ],
            order: [[1, 'desc']],

          "sAjaxSource": '<?php echo site_url($controller.'/GetListSN'); ?>',
          "oLanguage": {
            "sLengthMenu": "Menampilkan _MENU_ Data per halaman",
            "sZeroRecords": "Maaf, Data tidak ada",
            "sInfo": "Menampilkan _START_ s/d _END_ dari _TOTAL_ data",
            "sInfoEmpty": "Menampilkan 0 s/d 0 dari 0 data",
            "sSearch": "",
            "sInfoFiltered": "",
            "oPaginate": {
              "sPrevious": "Sebelumnya",
              "sNext": "Berikutnya"
          }
        }
      });
    }

  // });

  function blacklist(){

    $("#loading").show();
    $("#disablingDiv").show();
    $.ajax({
        type  : 'POST', 
        url   : '<?php echo site_url($controller.'/getBlacklistMishirin'); ?>', 
        success : function(data) {

          var html = '';

          var no = 1 ;
          const jsonData = JSON.parse(data);
          const dataArray = jsonData.data;
          dataArray.forEach(item => {
           
            var BLACKLIST_ID = item.blacklist_id;
            var xCREATED_BY = item.created_by;



			console.log(item.created_date);
            const timestamp = item.created_date;
            const date = new Date(timestamp);

            const year = date.getFullYear();
            const month = String(date.getMonth() + 1).padStart(2, '0');
            const day = String(date.getDate()).padStart(2, '0');
            const hours = String(date.getHours()).padStart(2, '0');
            const minutes = String(date.getMinutes()).padStart(2, '0');
            const seconds = String(date.getSeconds()).padStart(2, '0');

            const formattedDate = `${year}-${month}-${day}`;
            const formattedTime = `${hours}:${minutes}:${seconds}`;


            var DATE = formattedDate+' '+formattedTime;


            var RANGE_AWAL = item.range_awal;
            var RANGE_AKHIR = item.range_akhir;
            var KODE_BRG = item.kode_brg;
            var MESSAGE = "";
            var MESSAGE = item.message_external;
            var MESSAGE_INTERNAL = item.message_internal;
            var MOBILE = "#"+BLACKLIST_ID+"<br>"+DATE+"<br>"+xCREATED_BY+"<br>"+RANGE_AWAL+"<br>"+RANGE_AKHIR+"<br>"+KODE_BRG+"<br>"+MESSAGE+"<br>"+MESSAGE_INTERNAL;
            
            html += "<tr id='row_"+no+"'>"; 
            html += "<td class='hideOnMobile'>"+no+"</td>";
            html += "<td class='hideOnMobile'>"+DATE+"</td>";
            html += "<td class='hideOnMobile'>"+xCREATED_BY+"</td>"; 
            html += "<td class='hideOnMobile'>"+RANGE_AWAL+"</td>"; 
            html += "<td class='hideOnMobile'>"+RANGE_AKHIR+"</td>";
            html += "<td class='hideOnMobile'>"+KODE_BRG+"</td>";
            html += "<td class='hideOnMobile'>"+MESSAGE+"</td>";
            html += "<td class='hideOnMobile'>"+MESSAGE_INTERNAL+"</td>";
            html += "<td>";

            var toup = xCREATED_BY.toUpperCase();

            if(toup == '<?php echo strtoupper($_SESSION["logged_in"]["username"]); ?>'){
              html += "<a href = '#' data-href='<?php echo base_url(); ?><?=$controller?>/BlacklistDelete/"+BLACKLIST_ID+"' data-toggle='modal' data-target='#confirm-delete' data-record-title='"+KODE_BRG+" (No. Seri "+RANGE_AWAL+" sd "+RANGE_AKHIR+")'><i class='glyphicon glyphicon-trash'></a>"; 
            } else {
              html += "-";
            }

            html += "</td>";
            html += "<td width='100%' class='colMobile'>"+MOBILE+"</td>";
            html += "</tr>"; 

            no++;

          });
          document.getElementById('TblSN').innerHTML=html;

          table_blacklist = $('#TblBL').DataTable({
            "bProcessing": true,
            "pageLength": 10,
            "order": [[ 1, 'desc' ]]
          });
		  
			table_blacklist.on('order.dt search.dt', function () {
				let i = 1;
		 
			table_blacklist.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
					this.data(i++);
				});
			}).draw();
			
          klik = 1;
          $("#loading").hide();
          $("#disablingDiv").hide();
        }
    });
  }

  function deletedlist(){

      $('#TblBLDeleted').dataTable( {
          "bProcessing": true,
          "bServerSide": true,
           "columnDefs": [
            {"title":"ID","targets": 0,"className":"hideOnMobile"},
            {"title":"Brand","targets": 1,"className":"hideOnMobile"},
            {"title":"Product ID","targets": 2,"className":"hideOnMobile"},
            {"title":"Serial No. Min","targets": 3,"className":"hideOnMobile"},
            {"title":"Serial No. Max","targets": 4,"className":"hideOnMobile"},
            {"title":"Reason Deleted","targets": 5,"className":"hideOnMobile"},
            {"title":"Deleted By","targets": 6,"className":"hideOnMobile"},
            {"title":"History","targets": 7,"className":"colMobile"},
            ],
            order: [[1, 'desc']],

          "sAjaxSource": '<?php echo site_url($controller.'/getDeletedList'); ?>',
          "oLanguage": {
            "sLengthMenu": "Menampilkan _MENU_ Data per halaman",
            "sZeroRecords": "Maaf, Data tidak ada",
            "sInfo": "Menampilkan _START_ s/d _END_ dari _TOTAL_ data",
            "sInfoEmpty": "Menampilkan 0 s/d 0 dari 0 data",
            "sSearch": "",
            "sInfoFiltered": "",
            "oPaginate": {
              "sPrevious": "Sebelumnya",
              "sNext": "Berikutnya"
          }
        }

      });
      
    }
</script>
    